version: "3.1"

services:
  api:
    image: node:16
    container_name: api
    restart: always
    ports:
      - 3001:3001
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_NAME=orm_trybe_01
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - PORT=3001
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    command: bash
    tty: true
    stdin_open: true
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: container_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    