version: '3'
services:
  node:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: node:16-alpine
    container_name: offices_api
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    tty: true

    depends_on:
      - "database"
  database:
    container_name: offices_db
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: exercises
    ports:
      - "3306:3306"