version: "3.1"

services:
  api:
    image: node:16
    container_name: books_api
    restart: always
    ports:
      - 3001:3001
    environment:
      - DB_HOST=mysql
      - DB_NAME=books_database
      - DB_USER=root
      - DB_PASSWORD=password
      - SERVER_PORT=3001
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    command: bash
    tty: true
    stdin_open: true
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: books_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
